### ISSUE TITLE
增加搜索书签的功能

### ISSUE THREAD

**Issue by ji8czi** [leon-kfd/Dashboard#100]
能否增加搜索书签的功能呢？书签太多了，找起来费劲！

**Comment by leon-kfd** [comment]
这个场景应该使用的人不多，但可以考虑添加这个功能。能否提供一下你当前的页面截图，我想下UI怎么摆放。
有2个思路：
1. 直接在搜索栏组件可以配置同时搜索书签组件的数据内容
2. 书签组件添加右键菜单唤起搜索

**Comment by ji8czi** [comment]
感谢你的回复，这种场景不知道别人是否有需求，但是在书签非常多的情况下，直接能够搜索我觉得还是非常有必要的。我也使用过别的浏览器首页，都没有这个功能。
我觉得采用您说的第一种方式就挺好的，直接在搜索栏组件可以非常方便的搜索出书签来，点击就能直接访问书签网页。

**Comment by leon-kfd** [comment]
Done. 在线版([https://howdz.xyz](https://howdz.xyz))已实现，插件版需等待下一次发版。
![image](https://github.com/leon-kfd/Dashboard/assets/30256102/76fa2030-504e-4d91-9e6f-b2da4dd906d1)
![f03f576a585c4554698aed187e9f208](https://github.com/leon-kfd/Dashboard/assets/30256102/9fe403e9-0610-4393-9057-616cd016826c)
