### ISSUE TITLE
可以给默认样式适配一下浏览器暗色模式

### ISSUE THREAD

**Issue by fxzxmicah** [leon-kfd/Dashboard#105]
可以使用`prefers-color-scheme`的媒体查询来匹配，类似于这样：
```
@media (prefers-color-scheme: light) {
	:root {
		--color-a: #000;
		--color-a-active: #333;
		--color-body-bg: #fff;
	}
}
```

**Comment by leon-kfd** [comment]
因为起始页壁纸是自定义的，当前想到能应用暗黑样式的场景只有弹出框和右键菜单。
在没有预留css颜色变量的情况下，使用CSS的颜色翻转滤镜是实现暗黑主题的最快方式。
可以尝试在样式注入写入以下代码:
```
.easy-dialog-main,
.__menu__wrapper {
  filter: invert(1);
}
.easy-dialog-main img,
.__menu__wrapper img {
  filter: invert(1);
}
```
进行体验。

当然如果要自适应浏览器自动切换主题就要加入你上面提的媒体查询进行包裹了。
![image](https://github.com/leon-kfd/Dashboard/assets/30256102/92182bdb-6765-4cf4-9bc6-b2e988e2c63c)
![image](https://github.com/leon-kfd/Dashboard/assets/30256102/096c0ec3-fc17-40ab-be9f-ec91191574ab)
