### ISSUE TITLE
组件内链接设置为当前标签页打开

### ISSUE THREAD

**Issue by ayamir** [leon-kfd/Dashboard#107]
首先感谢作者这个项目，应该是我用过的新标签页扩展里面最舒服的一个了。
我只在书签的组件设置中看到了可以当前页面打开，但是比如GitHub Trending这种组件内的链接没办法当前页面打开，请问可以实现吗？

**Comment by leon-kfd** [comment]
考虑在下一版添加这个配置

**Comment by leon-kfd** [comment]
Done
