### ISSUE TITLE
希望能分别给中文和英文设置字体family

### ISSUE THREAD

**Issue by sayonaramemori** [leon-kfd/Dashboard#109]
如题

**Comment by leon-kfd** [comment]
![image](https://github.com/leon-kfd/Dashboard/assets/30256102/f6cabb08-784c-48c4-becc-1a5cc932ec05)
字体目前支持传入多个，用英文逗号+空格隔开。例如：`Comic Sans MS, 华文行楷`
需要英文字体写前面，然后后面写中文字体就可以实现了。
Preview: https://howdz.xyz?preview=1J9KL

**Comment by sayonaramemori** [comment]
Thanks for your reply. I make it successfully.
