### ISSUE TITLE
搜索栏可否不清空输入框，方便下次切换搜索引擎重新搜索

### ISSUE THREAD

**Issue by huainan1m** [leon-kfd/Dashboard#112]
当前是通过开启搜索历史记录来重新搜索。但是鼠标点击某条历史记录，不会输入到输入框里，只能通过上下键选中。还是有点不方便。

**Comment by leon-kfd** [comment]
目前大多数起始页搜索都是执行跳转后会清空输入框的，这样才更方便搜索，不用每次点清空。你这个属于低频操作，还不打算实现。
