### ISSUE TITLE
导航收藏页图标找不到会卡死

### ISSUE THREAD

**Issue by sunqqq1987** [leon-kfd/Dashboard#113]
edge的扩展
导航收藏页添加网站时候，如果图标找不到会卡死
https://kongfandong.cn/api/icon报了404 Not Found
建议https://kongfandong.cn/api/icon找不到也要发送一个图标
或者导航页这边处理一下异常

**Comment by leon-kfd** [comment]
/api/icon 这个接口好像没哪个地方会用, 之前改到/api/icon/v2了。可能插件是旧版本的原因，可以试着升级到最新版。目前/api/icon也做兼容处理了
