### ISSUE TITLE
电脑端在搜索栏输入内容后，无法使用下方显示的备选内容

### ISSUE THREAD

**Issue by KonakaSigma** [leon-kfd/Dashboard#115]
插件版本1.5.3

浏览器 Edge 127.0.2651.74

系统 Win 10（应该到不了这一层）

鼠标点击备选内容后备选栏消失，选择的内容不会进入搜索栏，只能用键盘来选择

**Comment by leon-kfd** [comment]
是指点击搜索词联想的内容吗？我试了下好像是正常的

**Comment by leon-kfd** [comment]
![Search](https://github.com/user-attachments/assets/4b36ec67-fd28-4c2f-932b-e24e4f15f4e3)

**Comment by KonakaSigma** [comment]
> 是指点击搜索词联想的内容吗？我试了下好像是正常的

是的，不知道是否为个例，重装后问题依旧存在

**Comment by leon-kfd** [comment]
可以使用在线版在其他浏览器试试， https://www.howdz.xyz/
那个点击有一个延时，不确定会不会是浏览器更新导致异常

**Comment by KonakaSigma** [comment]
> 可以使用在线版在其他浏览器试试， https://www.howdz.xyz/ 那个点击有一个延时，不确定会不会是浏览器更新导致异常

删除原配置文件后恢复正常（但是导入后还是有问题），需要重新配置了
