### ISSUE TITLE
将链接或书签拖动到"导航收藏页"时自动设置

### ISSUE THREAD

**Issue by yunzlp** [leon-kfd/Dashboard#117]
可能场景
1,从顶部书签栏拖动书签到"导航收藏页"
这个是纯链接字符串,所以拖进去后应尝试获取链接对应title与ico

2,其他地方拖入的符合条件的链接字符串到"导航收藏页"
同上

3,将"书签导航"内的书签拖动到"导航收藏页"

**Comment by leon-kfd** [comment]
初步验证应该可以实现，尝试在下一版本新增。

**Comment by leon-kfd** [comment]
https://codepen.io/leon-kfd/pen/ZEdwBLw

**Comment by leon-kfd** [comment]
Done
