### ISSUE TITLE
书签管理的书签名显示过短应鼠标hover时弹出详细信息

### ISSUE THREAD

**Issue by yunzlp** [leon-kfd/Dashboard#119]

**Comment by leon-kfd** [comment]
悬停title将加下一版本新增。

另应对比较长的title也可试试这个配置：
![image](https://github.com/user-attachments/assets/736fae63-da95-4fbf-aaa4-3b02dc3e2d88)

**Comment by leon-kfd** [comment]
40c0ac541015ea297759690e4b1d7886b24f6306
