### ISSUE TITLE
建议适配手机版网页

### ISSUE THREAD

**Issue by aheig** [leon-kfd/Dashboard#21]
建议适配手机版网页

**Comment by leon-kfd** [comment]
项目支持响应式的，不过手机端上设置是比PC端麻烦一点。只是当前没有手机端的主题预设，后面会加。

![mobile](https://user-images.githubusercontent.com/30256102/137605368-68336957-7608-461d-9ae0-ab1b660db2e3.png)

后面先加类似上图这种主题。

**Comment by leon-kfd** [comment]
已增加2个手机主题预设
