### ISSUE TITLE
请求增加在当前页面打开网页的选项

### ISSUE THREAD

**Issue by DustyNight** [leon-kfd/Dashboard#24]
作为new tab，我觉得在打开我想要的网页之后，它就没必要存在了，但是现在（起码我周五使用的时候还是）所有新打开的网页都是后台新tab，希望能够增加选项，让用户决定新页面是在当前tab打开还是后台打开

**Comment by leon-kfd** [comment]
![image](https://user-images.githubusercontent.com/30256102/139607718-8d103021-176f-43ba-82f9-dd57a2f1bb48.png)

物料 Collection和Search 已经添加了这个配置。

好像上周已经更新了，可以检查一下当前是否最新版。

**Comment by DustyNight** [comment]
确实，不好意思，我把issue关了
