### ISSUE TITLE
建议增加壁纸随机图片的间隔刷新

### ISSUE THREAD

**Issue by DustyNight** [leon-kfd/Dashboard#34]
现在使用随机壁纸功能的时候，每一次打开新的标签页，都会获取新的壁纸。在网络环境一般的时候，每次都要一到两秒才能把壁纸刷出来，体验有点差。希望可以增加一个配置时间，每隔多长时间才会去刷新一次壁纸。

**Comment by leon-kfd** [comment]
感谢反馈，之前也发现随机壁纸功能在国内网络访问体验很差，所以最近增加了新浪随机壁纸，国内网络加载应该还行。

对于随机壁纸定时切换这个功能，**后面应该是会加入的**。但是这个并不会改善初次加载的速度，因为基于当前随机壁纸是直接使用http接口api地址，最终的壁纸图片并不会跑service worker缓存。不过也说不准后面可以改壁纸组件的架构。

**Comment by leon-kfd** [comment]
Done.
