### ISSUE TITLE
为什么搜索引擎没有chrome

### ISSUE THREAD

**Issue by Shuang-Zi** [leon-kfd/Dashboard#35]

**Comment by leon-kfd** [comment]
Chrome搜索引擎？你指的应该是Google吧？
搜索引擎可以在组件配置自己配置。更改顺序、自定义添加等都可以。
![切换引擎.gif](https://s2.loli.net/2021/12/29/8Wp6DCMzNRmQhHt.gif)

**Comment by Shuang-Zi** [comment]
奥奥，谢谢
