### ISSUE TITLE
你好，项目很棒，但是我这边遇到了一个词条跳转问题

### ISSUE THREAD

**Issue by yxj1028530975** [leon-kfd/Dashboard#37]
掘金知乎等热搜词条在锁定状态下无法跳转，点击logo只能跳转到首页。但是在编辑状态下可以进行词条跳转，这是我未配置正确的原因吗，麻烦指教下。

**Comment by leon-kfd** [comment]
感谢反馈，确实是一个bug。是最近的一次更新导致的，把逻辑搞反了。我现在修复一版，网页版会几分钟后更新，chrome插件版本会尽快发布。

**Comment by leon-kfd** [comment]
Fixed
