### ISSUE TITLE
workbox-sw.js 是在干啥？

### ISSUE THREAD

**Issue by wuhou123** [leon-kfd/Dashboard#4]
功能很多，文档要跟上了

**Comment by leon-kfd** [comment]
workbox是一个Service Worker框架，主要利用sw将一些图片等静态资源进行缓存，在main.js会检测如果浏览器支持sw就会开启，workbox在这里是本地加载，所以在public里面会有

**Comment by wuhou123** [comment]
> workbox是一个Service Worker框架，主要利用sw将一些图片等静态资源进行缓存，在main.js会检测如果浏览器支持sw就会开启，workbox在这里是本地加载，所以在public里面会有

哦，看到里面有个https://storage.googleapis.com/workbox-cdn/releases/6.1.5，以为有统计埋点啥的
