### ISSUE TITLE
建议：是否可以将数据保存到服务器中实现多平台多浏览器无缝衔接

### ISSUE THREAD

**Issue by b1tzer** [leon-kfd/Dashboard#43]
希望能加入此功能，并实现权限管理，允许公开或私有数据。

不过挂在服务器其实也都是给自己用的，单独设置每一项公开还是私有好像也没太大意义。您酌情处理。

希望项目越来越好。

**Comment by leon-kfd** [comment]
当前是可以通过生成随机**密钥**进行数据同步的。
![image](https://user-images.githubusercontent.com/30256102/149615321-a2cd064a-bcb4-4db1-a581-87332b9d80c9.png)

之前也考虑过引入**账号系统**进行数据**无感定时同步**，但考虑到当前服务器可能无法承受后面如果用户量增多后的并发压力，所以暂时未实现，后面看情况吧。
