### ISSUE TITLE
建议增加模态框动画效果开关

### ISSUE THREAD

**Issue by hipig** [leon-kfd/Dashboard#49]
建议增加模态框动画效果开关，在一些低配置的电脑上运行，容易卡死

**Comment by leon-kfd** [comment]
感谢反馈，我记得之前就有人反馈过，忘了做了。有空加上。
不过也有可能是我自己写的弹窗组件的性能问题，看下加上关闭动画会怎样。

**Comment by leon-kfd** [comment]
Done.

![image](https://user-images.githubusercontent.com/30256102/150619525-ef0fdf70-bf0e-4393-b99b-9472b0d9859d.png)

网页版已更新，在全局配置可以开启是否禁用弹窗动画。

**Comment by hipig** [comment]
> Done.
> 
> ![image](https://user-images.githubusercontent.com/30256102/150619525-ef0fdf70-bf0e-4393-b99b-9472b0d9859d.png)
> 
> 网页版已更新，在全局配置可以开启是否禁用弹窗动画。

浏览器插件版更新了吗

**Comment by leon-kfd** [comment]
@hipig 插件一般没那么快发布，要商店审核。可能年后会有一版，一般会等几个更新才合一个版本
