### ISSUE TITLE
关于中英文空格的问题

### ISSUE THREAD

**Issue by hu3rror** [leon-kfd/Dashboard#51]
Hi，无论如何先感谢做出这个项目。

有一个关于命名的建议，目前的命名为 `Howdz起始页`，`Howdz` 与 `起始页` 之间是没有空格的，参考[中英文排版指南](https://github.com/aaranxu/chinese-copywriting-guidelines#%E7%A9%BA%E6%A0%BC)中的说明，中英文之间应尽量添加上空格，即 `Howdz 起始页`。一方面符合排版规范，另一方面也让字符的显示更和谐一些，能突出 `Howdz` 本身。

感谢阅读:)

**Comment by leon-kfd** [comment]
感谢反馈，命名习惯问题，看下后边要不要统一改吧。
另目前`Howdz起始页`好像只在document.title中显示，这个是可以配置的。
![屏幕截图 2022-02-13 101409](https://user-images.githubusercontent.com/30256102/153735355-e7ffe248-fad8-4d37-84e0-2d73f65e6204.png)

**Comment by hu3rror** [comment]
> 感谢反馈，命名习惯问题，看下后边要不要统一改吧。 另目前`Howdz起始页`好像只在document.title中显示，这个是可以配置的。 ![屏幕截图 2022-02-13 101409](https://user-images.githubusercontent.com/30256102/153735355-e7ffe248-fad8-4d37-84e0-2d73f65e6204.png)

感谢回复，这个我之前已经修改了，就是考虑到这个问题所以才特意发一下 Issue XD
