### ISSUE TITLE
大佬  有没有编译好的分享

### ISSUE THREAD

**Issue by benlvcc** [leon-kfd/Dashboard#53]
大佬  源码非常漂亮 能不能更新时候分享一份编译好的源码 谢谢

**Comment by leon-kfd** [comment]
私有部署请执行 `npm i && npm run build:crx`然后把crx文件部署到自己服务器，再利用nginx参考`vite.confgi.ts`的`proxy`配置后端接口反向代理，否则无法使用例如天气、热搜类等组件。

**Comment by benlvcc** [comment]
老哥 您能给编译一份发给我下吗&nbsp; 我实在不会，但我特喜欢你这个 我找人编译了一个 接口全部跨了 麻烦了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月23日(星期三) 上午8:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leon-kfd/Dashboard] 大佬  有没有编译好的分享 (Issue #53)





 
私有部署请执行 npm i &amp;&amp; npm run build:crx然后把crx文件部署到自己服务器，再利用nginx参考vite.confgi.ts的proxy配置后端接口反向代理，否则无法使用例如天气、热搜类等组件。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by benlvcc** [comment]
老哥 是不是我把build:crx这个放到服务器根目录 然后把vite.config.ts文件也放到根目录 把里面的域名修改成我自己的域名吗 还是怎么配置呢 老哥 有没有群交流呢

**Comment by leon-kfd** [comment]
因为大部分接口都没有开放跨域，自己私有部署可以通过配置`nginx`反向代理解决接口跨域问题。如果实在不会又想用，我可以单独给你的域名开放，可以把你服务器域名私发给我，并确保是尽可能是https的域名。
