### ISSUE TITLE
要求：英语和谷歌支持

### ISSUE THREAD

**Issue by darkmaster434** [leon-kfd/Dashboard#55]
我非常喜欢这个扩展。 但它不支持英语。 以及搜索栏中没有谷歌搜索。 提供英语和谷歌支持将是我的谦卑要求。 我不知道如何进行扩展，否则我会尝试这样做。 感谢您制作了这个惊人的扩展。 顺便说一句，我不懂中文，我只是用谷歌翻译。

**Comment by leon-kfd** [comment]
You can add Google Search in this way.
![add-chrome-search.gif](https://s2.loli.net/2022/03/05/SyqRCpi34QP62KA.gif)

**Comment by leon-kfd** [comment]
This project currently only supports Chinese，Multiple languages may be added in the future. 
But the Back-end services for some components, such as weather components, are not available outside of China. 
All of this could be solved in the future, but as an individual developer, I don't seem to have much time to do it.

**Comment by darkmaster434** [comment]
Thank you. I totally get your point. I hope one day there will be multi-language support.

**Comment by leon-kfd** [comment]
![image](https://user-images.githubusercontent.com/30256102/158496885-5167ee13-664b-488a-af32-d1068e9c5e70.png)
Multiple languages is supported in the latest version (v1.2.2), suport english now.

**Comment by darkmaster434** [comment]
Thank you So much
