### ISSUE TITLE
Without internet icon and images not showing. Also there is no way to add images from local storage.

### ISSUE THREAD

**Issue by darkmaster434** [leon-kfd/Dashboard#57]
Everything is pretty good. I am enjoying it so much. however, whenever I open a new tab it takes some time to show the wallpaper. Also without the internet, the icon and wallpaper are of no use. It would be great if it store these image files in local storage then fetch them from there. Also if there is an option to load the local storage video or images as wallpaper it will be great. Maybe in the future, these functions will come.  I am eagerly waiting

**Comment by leon-kfd** [comment]
Despite using the service worker, the site cannot be used offline. I have also considered caching images in Localstorage, but Chrome localstorage is limit in 5M, some Hd wallpapers easily exceed this limit. But I'll think of other ways to see if I can do that. (Maybe chrome extension storage).

**Comment by darkmaster434** [comment]
I found an inconvenient way to use local files. I used HFS as localhost then use than paste my localhost's files URL on the dynamic wallpaper box. and it worked. in this way, any video or gif could be hosted. but it is super inconvenient.

**Comment by leon-kfd** [comment]
There is a new feature to upload local file for wallpaper.
