### ISSUE TITLE
搜索引擎Bing无法直接调用

### ISSUE THREAD

**Issue by xffuxka** [leon-kfd/Dashboard#59]
开发者您好。
在用版本1.2.4，浏览器Chrome for Mac。近期使用过程中发现搜索引擎Bing的调用似乎出现了问题。
具体表现为在搜索栏使用Bing国际版和/国内版输入内容后不能直接搜索内容而是跳出了Bing的空白页，需要再次键入搜索内容。
用百度的话似乎不会出现这个情况。
感谢您的开发的扩展程序，一直以来都很喜欢。
祝好。

**Comment by leon-kfd** [comment]
最近几个版本好像都没改过搜索组件的逻辑。
暂无环境调试排查和重现，希望可以参照以下几点协助排查。
1. 使用其他输入法看下会不会重现
2. 看下跳转地址是否有携带搜索的关键词字符串
3. 更改一下搜索栏跳转方式（当前页与新窗口）
4. 若以上都无法重现，我试一下配置一个自定义搜索引擎给你试试
