### ISSUE TITLE
载入时插件版的下拉动画后会有一个向右居中小位移 网页版则正常

### ISSUE THREAD

**Issue by Yoooooo** [leon-kfd/Dashboard#60]
小位移显得动画不流畅了 而网页版则没有这个问题 正常下拉动画就加载完了
浏览器是Edge 浏览器版本 101.0.1210.32 插件版本 1.2.4
导入是相同的配置文件 即便是用默认配置的“基础+动态主题” 依然有这个问题

**Comment by leon-kfd** [comment]
确实是稳定重现。暂时还未定位到问题，后面抽空再看一下。感谢反馈。

**Comment by Yoooooo** [comment]
额。。1.2.5 问题是解决了 动画也没了。。。确认没有禁用动画。。。还是说故意这样的?

**Comment by leon-kfd** [comment]
已经去除栅格模式下插件的transform动画。
