### ISSUE TITLE
collection无法添加墙外链接

### ISSUE THREAD

**Issue by nebel-dev** [leon-kfd/Dashboard#61]
开着或关闭代理都是这样

**Comment by leon-kfd** [comment]
应该是可以添加的，只是不能自动获取到网站图标。在添加图标的时候使用文字图标或网络图片即可。
![image](https://user-images.githubusercontent.com/30256102/168557887-0e04f52e-d9c1-4052-afc7-119342d42893.png)

**Comment by nebel-dev** [comment]
> 应该是可以添加的，只是不能自动获取到网站图标。在添加图标的时候使用文字图标或网络图片即可。 ![image](https://user-images.githubusercontent.com/30256102/168557887-0e04f52e-d9c1-4052-afc7-119342d42893.png)

你这个是在bookmark中编辑的，在collection组件中我一直无法添加
![QQ截图20220516172857](https://user-images.githubusercontent.com/24634673/168562607-c020dd85-f9c5-4e41-a17d-0d2e82e561c4.png)

**Comment by leon-kfd** [comment]
哦，你指的是Collection组件，那个确实是只能等自动获取图标完成才能添加。后续应该更新Collection的添加跟Bookmark一样。是考虑不到的点，不过还是推荐用Bookmark多一点。

**Comment by nebel-dev** [comment]
> 

原来是这样，我是想把常用的放在collection一键打开，bookmark就放在了新建的标签页。
感谢分享！

**Comment by nebel-dev** [comment]
> 哦，你指的是Collection组件，那个确实是只能等自动获取图标完成才能添加。后续应该更新Collection的添加跟Bookmark一样。是考虑不到的点，不过还是推荐用Bookmark多一点。

原来是这样，我是想把常用的放在collection一键打开，bookmark就放在了新建的标签页。
感谢分享！
