### ISSUE TITLE
在页面无单击交互的地方双击会打开collection中“C”键设置的链接

### ISSUE THREAD

**Issue by nebel-dev** [leon-kfd/Dashboard#62]
我用的模板是多组件预设

**Comment by nebel-dev** [comment]
我用的模板是多组件预设

**Comment by leon-kfd** [comment]
好像没有加过双击事件逻辑，是否按下了C键而已？或者在组件设置关掉快捷按键看是否会重现。
![image](https://user-images.githubusercontent.com/30256102/168564662-d0296857-4b56-4f95-b60f-1499163f0d70.png)

**Comment by nebel-dev** [comment]
> 好像没有加过双击事件逻辑，是否按下了C键而已？或者在组件设置关掉快捷按键看是否会重现。 ![image](https://user-images.githubusercontent.com/30256102/168564662-d0296857-4b56-4f95-b60f-1499163f0d70.png)

没有按下C键，关闭collection的“快捷按键”确实不会重现，不过这样就没法用快捷键打开页面了
正常使用是没有问题的，毕竟没事也不会去双击
感谢分享！
