### ISSUE TITLE
希望添加搜索框选择删除某条记录的功能

### ISSUE THREAD

**Issue by Lyrikp** [leon-kfd/Dashboard#66]
当前版本中搜索框记录有一次全部清除历史记录的按钮，希望能添加一个单独删除某条记录的按钮，像百度首页搜索框的记录删除功能一样即可。

搜索框记录在一定程度上会充当收藏夹/常用搜索的功能，因为一些一次性搜索记录挤占掉常用搜索记录的位置有些不妥，而且重复搜索历史记录中的关键词，记录的顺序并不会更新保持置顶，这种不是因为时间权重而是综合新出现于时间权重的排序方式会让记录被没有出现过的关键词挤占掉位置。

**Comment by leon-kfd** [comment]
这个功能比较简单，有空加一下，请期待

**Comment by leon-kfd** [comment]
Done.
https://github.com/leon-kfd/Dashboard/commit/25b1384b765f6ef335626d01e89183a30d606171

**Comment by Lyrikp** [comment]
Check. 感谢开发者！
