### ISSUE TITLE
feature: 全局背景支持本地图片

### ISSUE THREAD

**Issue by subframe7536** [leon-kfd/Dashboard#67]
V2EX来的，使用时发现网络原因会导致全局背景加载延迟，希望支持加载本地图片（如果支持多张随机就更好了

**Comment by leon-kfd** [comment]
1、当前在线版是会把当前背景图缓存都service worker，第二次进入会先展示缓存的这张，当随机图加载完再切换（插件版未发布）
2、使用本地图片暂时不考虑，浏览器并不能直接读取本地文件，虽然可以把图片先转为base64然后存到localStorage，但浏览器localStorage的上限为5M，考虑到当前很多高清图都有可能超过这个限制，所以并不想做
3、当前自定义图片可以先把图片上传到cos，然后指定网络路径即可（这种也能被service worker缓存）

**Comment by subframe7536** [comment]
emmm...indexDB应该也可以存吧
这个是我之前在用的，[源码](https://github.com/joelshepherd/tabliss/blob/6b42178cb49d234bd785f18c443c526bd51e466b/src/plugins/backgrounds/image/ImageSettings.tsx)

**Comment by leon-kfd** [comment]
IndexDB也是一种方案，后面有空可以研究一下。感谢反馈

**Comment by leon-kfd** [comment]
Done.
