### ISSUE TITLE
希望增加点击空白地方关闭文件夹功能

### ISSUE THREAD

**Issue by Tender08** [leon-kfd/Dashboard#68]
在打开文件夹后，如果发现点错了，必须点击右上角才能关闭，希望增加点击空白地方关闭文件夹功能

**Comment by leon-kfd** [comment]
是否指书签物料的文件夹，当前已有配置项可设置。
![image](https://user-images.githubusercontent.com/30256102/184817596-3e047913-926c-4031-b423-740cd1071557.png)

**Comment by Tender08** [comment]
> 是否指书签物料的文件夹，当前已有配置项可设置。 ![image](https://user-images.githubusercontent.com/30256102/184817596-3e047913-926c-4031-b423-740cd1071557.png)

找到该功能啦，感谢！给你一个star
