### ISSUE TITLE
未来会有firefox插件吗？

### ISSUE THREAD

**Issue by xubooo2** [leon-kfd/Dashboard#72]
请问，
未来会有firefox的插件吗？
该插件的设置等数据是否保存在云端？

**Comment by leon-kfd** [comment]
暂时还没上架firefox插件商店哦，你使用`npm run build:crx`打包crx文件夹或压缩包然后以开发者模式导入到firefox中。
另外浏览器的所有配置可以通过在左下角的辅助功能=》导入导出中生成随机密钥来进行多设备同步。数据会暂存在服务器7天。
当前系统因服务器压力问题，暂未实现帐号系统实时同步云端的功能。
![image](https://user-images.githubusercontent.com/30256102/195994861-b30ca651-efe1-4c73-a2c1-a0b104c0a5c6.png)
