### ISSUE TITLE
搜索框显示优化

### ISSUE THREAD

**Issue by jiaojiaodubai** [leon-kfd/Dashboard#74]
希望增加几个特性：
- 搜索框字体支持添加阴影，以便在浅色背景时依旧能突出显示浅色文字；
- 搜索框字体可调节字体大小，搜索框高度保证安全内边距的前提下根据字号自适应变化；
- 搜索框的边框颜色支持修改颜色或调至透明，而不是仅支持调整搜索框内部填充颜色；
- 搜索框的联想提示框可调节圆角宽度，或默认继承搜索框的圆角设置；
- 书签导航栏应支持纯文字标签模式（不使用图标以展示更多标签）；
- 书签导航栏的详情弹窗应同样支持背景颜色和圆角的更改。

**Comment by leon-kfd** [comment]
搜索框Search组件那几个都属于CSS样式，当前在我不加代码的情况下，用户也能自定义CSS来实现。例如搜索框文字阴影，可参考以下步骤设置：
1. 给搜索框设置ID值
2. 找到搜索框对应的类名，然后在全局设置注入CSS代码
![1666141553875](https://user-images.githubusercontent.com/30256102/196574038-aac76116-7cda-42a8-8f64-5b710acae29e.jpg)

![1666141813965](https://user-images.githubusercontent.com/30256102/196574051-c0a34c0a-543a-4e94-b0ff-a977606750f4.jpg)

Result: 
![1666141791365](https://user-images.githubusercontent.com/30256102/196574081-10713ca2-fc3f-4a7f-8d28-4212d4cbe3d7.jpg)

字体大小设置同理，使用font-size属性。

另感谢建议，部分优化我会考虑添加。

**Comment by jiaojiaodubai** [comment]
> 

感谢回复，第一次没有操作成功，第二次参考源码的样式选择成功了。现在还有两个小问题：

1. 目前搜索框设置聚焦背景动画后，被虚化的仅是壁纸，如果搜索框下方还有书签导航，则书签导航内的图标是不会被虚化的。如果用户设置把搜索提示面板设置得较为透明（正如你上一条回复中所展示的那样），那搜索提示面板背后的的图标就会透过面板从而降低文字可读性。现在我通过降低提示面板的透明度，并增加背景模糊来解决这一问题：
  `#MySearchBox .link-search-wrapper {
    border-radius: 20px;
    background: rgba(0, 0, 0, 0.7);
    backdrop-filter: blur(5px)!important;
  }`
  不过，如果自带的聚焦背景画默认就能连同书签导航一并虚化，或许会更好: )。
3. 右下角设置按钮图标不能隐藏，颜色也不能更改，在用户配置了非蓝色的主题时，这个小按钮会非常吸刺眼。我尝试通过注入
  `.menu-open-button, .menu-item {
    background: rgba(138, 138, 138,0.49);
  }`
  来设置按钮的颜色，但并没有成功，目前暂时使用的是[Chrome的Local Override](https://developer.chrome.com/blog/new-in-devtools-65/#overrides)来解决这个问题，但这个方法只有开启开发者工具后才能生效，并不是一个太好的解决方法。是我注入的代码有问题吗？还是目前还不支持修改那个蓝色按钮的颜色呢？

**Comment by leon-kfd** [comment]
第一点你试试是不是开启毛玻璃配置能解决你的问题
![image](https://user-images.githubusercontent.com/30256102/196867056-9eaea2c6-ad1e-4ece-87d7-a8d1ac21b143.png)
![image](https://user-images.githubusercontent.com/30256102/196867103-ea56fb06-5b03-4e12-8831-2102f8db9355.png)
