### ISSUE TITLE
建议支持下Lively Wallpaper

### ISSUE THREAD

**Issue by xxxily** [leon-kfd/Dashboard#75]
插件很好用！

建议网页版：https://s.kongfandong.cn/ 支持嵌入到[Lively Wallpaper](https://github.com/rocksdanister/lively)里面
这样就可以作为桌面级乃至屏保级的Dashboard了

提供下个人的实现思路：
支持URL传参指定保存和读取配置接口的地址（接口地址跟用户是否登录无关），
这样设置好后在Lively Wallpaper端也输入相同参数URL就可以直接打开展示了
而配置端还是在浏览器里

**Comment by xxxily** [comment]
另外也可以预置几套默认配置，使用不同的参数进行访问

自定义接口地址可以是只读的，用户将自己定义好的JSON配置导出，然后托管在自己的服务器里
（只读的话安全性好一些，但就是缺少了灵活性）

**Comment by leon-kfd** [comment]
明白你的意思，例如访问：https://s.kongfandong.cn?q=xxxx/config.json 是可以直接将q后面的网络接口json在初始化时fetch出来当配置。这种实现难度不高，主要还是安全问题。这样相当于域名路径持久性使用，很多东西基于国内互联网的一些政策，如果不经过审核的话会有安全问题，可能我服务器都会被封掉。
当然，可以自己fork下来私有化部署也能解决，使用vercel、netlify之类来挂就行。
