### ISSUE TITLE
希望可以支持使用本地视频做背景

### ISSUE THREAD

**Issue by magblank** [leon-kfd/Dashboard#76]

**Comment by leon-kfd** [comment]
没找到能实现的思路。当前浏览器不能直接持久性读取本地文件，当前的本地图片实现是将图片转成base64保存到indexDB里面。视频的话占用太大，而且还有编码问题，这种方式并不合适。

**Comment by leon-kfd** [comment]
网络视频做壁纸已支持的，请参考动态壁纸。
![image](https://user-images.githubusercontent.com/30256102/199632254-513bf84f-b0fa-4001-9545-a74dfebdd1ff.png)

**Comment by xxxily** [comment]
> 网络视频做壁纸已支持的，请参考动态壁纸。 ![image](https://user-images.githubusercontent.com/30256102/199632254-513bf84f-b0fa-4001-9545-a74dfebdd1ff.png)

支持随机动态壁纸吗？或者支持指定多个动态壁纸进行随机轮播也行
