### ISSUE TITLE
请求可以通过docker来部署网页版，实现IOS手机的使用

### ISSUE THREAD

**Issue by ZevaXu** [leon-kfd/Dashboard#81]
如题，浏览器版用了感觉很好，但是ios手机没法使用，希望加入docker自部署网页版，这样就可以通过手机来访问！

**Comment by leon-kfd** [comment]
项目兼容手机端。手机端可以直接访问网页版: https://s.kongfandong.cn

![26d8d9a90aae44072c3065dbb33ae1c](https://user-images.githubusercontent.com/30256102/204979928-61efc417-93d4-4e27-823e-3ef5633318a0.jpg)

当前暂无Docker部署，可自己clone项目打包。项目为纯前端工程，但项目涉及后端部分接口需要配置反向代理。

**Comment by chunln** [comment]
同求docker部署

**Comment by leon-kfd** [comment]
我对docker部署，而且这个项目属于纯前端项目。自己可以打包出静态资源目录放到任意服务器（nginx,apach,IIS等都行）,不过部分物料组件需要访问接口的，需要配一下反向代理到我服务器，不然会报跨域。
打包命令：`npm run build:crx`
