### ISSUE TITLE
新标签页图标未显示

### ISSUE THREAD

**Issue by fxzxmicah** [leon-kfd/Dashboard#86]
![image](https://user-images.githubusercontent.com/48860358/218312145-42686b63-5648-4f6c-bcc9-72ef6c08dddf.png)
新标签页未显示网页图标。
使用的是Edge浏览器扩展。

**Comment by leon-kfd** [comment]
好像是当前图标过大或者不是纯色图标，尝试在下一版解决。

**Comment by leon-kfd** [comment]
Done.
