### ISSUE TITLE
搜索栏不能自定义高度，只能自定义宽度

### ISSUE THREAD

**Issue by via-liabs** [leon-kfd/Dashboard#87]
![image](https://user-images.githubusercontent.com/100687450/219006787-8ca0c126-c33e-4be0-a17a-508a45e08164.png)

**Comment by leon-kfd** [comment]
搜索组件的高度并没设置可配置项。但你可以通过注入CSS的方式实现，在全局配置的CSS注入，写入以下代码即可：
```
.search-wrapper-box {
  height: 120px !important;
}
.engine-selector, .link-search-wrapper {
  top: 124px !important;
}
```
搜索联想和引擎切换的弹出浮窗也需要同时修改位置，不然会出现遮挡。
效果：
![image](https://user-images.githubusercontent.com/30256102/219232428-4d7f4425-eb5c-4335-af93-16c76ef2013f.png)
