### ISSUE TITLE
另一种设置为手机浏览器首页的方法

### ISSUE THREAD

**Issue by fxzxmicah** [leon-kfd/Dashboard#88]
可以通过将浏览器首页设置为`file:///sdcard/.../index.html`来使用，这样从本地加载资源可以极大地加快打开速度。
不过我不清楚这样的话自定义设置还能不能正常保存。
此外，目前的代码也不支持这样使用。

**Comment by leon-kfd** [comment]
浏览器应该不能使用本地文件这个协议作为浏览器起始页的，而且本地文件协议请求接口会报跨域。

**Comment by fxzxmicah** [comment]
> 浏览器应该不能使用本地文件这个协议作为浏览器起始页的

在我的手机上是可以的。

> 而且本地文件协议请求接口会报跨域

这个我倒是不清楚，所以我只是提一下想法，看看有没有可能这样用。
