### ISSUE TITLE
什么都没有设置，背景图片突然变得模糊

### ISSUE THREAD

**Issue by Latucc** [leon-kfd/Dashboard#89]
而且全局设置里面也没有加滤镜。系统是win11 22h2 22621.1344

**Comment by leon-kfd** [comment]
1. 背景壁纸再切换加载时会有一个高斯模糊过度，可以检查一下网络，可切换其他随机壁纸源或停用随机壁纸试试
2. 搜索组件可能设置了聚焦时背景虚化，可关闭试试

![image](https://user-images.githubusercontent.com/30256102/222996613-4180411b-1e9c-46bb-87bf-6d0a1c320ffd.png)

![image](https://user-images.githubusercontent.com/30256102/222996584-ce834930-3ea1-4f01-80d2-027a0cd0ab3a.png)

**Comment by Latucc** [comment]
> 而且全局设置里面也没有加滤镜。系统是win11 22h2 22621.1344
