### ISSUE TITLE
喜欢能够增加设置默认搜索引擎的功能

### ISSUE THREAD

**Issue by flashliao** [leon-kfd/Dashboard#90]
喜欢能够增加设置默认搜索引擎的功能，不喜欢综合搜索

**Comment by leon-kfd** [comment]
当前已支持自定义添加搜索引擎。
![image](https://user-images.githubusercontent.com/30256102/223302594-aef9d3f2-9b52-49f0-9b08-5f3f0a7684f9.png)
![image](https://user-images.githubusercontent.com/30256102/223302647-e94da893-9557-4de5-885b-701de3317ce7.png)
通过拖拽切换引擎的顺序。
