### ISSUE TITLE
可不可以支持自己选择部分书签导入的功能？

### ISSUE THREAD

**Issue by sy999999ys** [leon-kfd/Dashboard#91]
像MONKNOW 标签页那样的
![image](https://user-images.githubusercontent.com/51683562/225822476-9440ad3d-b0ac-430d-b13b-e61cb3f99393.png)

**Comment by leon-kfd** [comment]
当前书签组件的导入是全量的，而且只支持一层子目录。多层子目录和按需导入的功能后面我看看有没有空做吧

**Comment by sy999999ys** [comment]
好的，谢谢
