### ISSUE TITLE
導航收藏頁 是否有更多的彈性

### ISSUE THREAD

**Issue by KamiyaMinoru** [leon-kfd/Dashboard#93]
一般dashboard有更視覺化的顯示 用圖示 尤其是自定義圖示 會讓使用者更能一目了然想要點擊或尋找的物件
我稍微試用了一下 發現只能選擇URL和說明文字 但一顆小小的cap其實塞不下remark
不知道要怎麼修改讓它看起來更美觀 或者更自由
![image](https://user-images.githubusercontent.com/78710607/228405598-9b101105-1f7f-4a27-a47f-bc7b559266c3.png)

也不希望受限在對應鍵盤的layout, 因為有時候放在桌面或書籤的連結包含了很多同個domain的相近網站 這樣不太好硬放在鍵盤對應

**Comment by leon-kfd** [comment]
![image](https://user-images.githubusercontent.com/30256102/228408277-0600b80b-3a3e-4b42-883e-3aa15973f096.png)
先尝试增加这个值。
