### ISSUE TITLE
标题间隔调小时，图标会变大，但是最后一个多余的不会变

### ISSUE THREAD

**Issue by imaliang** [leon-kfd/Dashboard#95]
![image](https://github.com/leon-kfd/Dashboard/assets/53564732/b3033c98-3c88-4180-9e42-f5e0341f8489)

**Comment by imaliang** [comment]
标题写错了，是 按键间隔调小时，图标会变大，但是最后一个不会变

**Comment by leon-kfd** [comment]
fixed. 网页在线版已更新，Chrome插件需等下一次版本更新。
或者可以在全局设置的CSS样式注入写入以下代码临时解决：
```
.material-collection .keys-wrapper:last-child {
  padding: 2px !important;
}
```
替换相应间隔padding即可。
