### ISSUE TITLE
希望增加一个简单的新功能，一键打开预设的网站

### ISSUE THREAD

**Issue by sadtear** [leon-kfd/Dashboard#96]
很喜欢这个标签页，自定义性很强。希望增加一个新功能，就是设置一个按钮之类的，或者小组件。可以把预设的url列表一键打开！

**Comment by leon-kfd** [comment]
当前已经有组件是可以实现了。
1. 书签导航组件
2. 键盘收藏夹组件
3. 利用空组件，然后配置点击交互行为

可能你是选了简洁主题所以没有，如果不会自己配就在辅助功能清掉数据重新进入，然后选择第二或者第三个主题试试。
