### ISSUE TITLE
求问大佬怎么把这个项目变成浏览器插件呢

### ISSUE THREAD

**Issue by zhangsan08** [leon-kfd/Dashboard#98]
求问大佬怎么把这个项目变成浏览器插件呢，我看项目内没有关于浏览器插件的配置。我想把它改成我喜欢的样子，让它成为的我新标签页

**Comment by leon-kfd** [comment]
https://github.com/leon-kfd/Dashboard/blob/main/public/manifest.json
这个就是浏览器插件的配置，项目执行npm run build:crx就会打包出crx文件夹，这个就是浏览器扩展的文件夹。开发者模式下可以在Chrome中使用。
例外，这个项目本来就已经有发布浏览器插件：
https://chrome.google.com/webstore/detail/howdz%E8%B5%B7%E5%A7%8B%E9%A1%B5/ggglfehkglgpenacfalffmiojghklamm/related
