### ISSUE TITLE
无法添加file协议到主页书签

### ISSUE THREAD

**Issue by fxzxmicah** [leon-kfd/Dashboard#99]
打开`file:///`协议的书签会被修改为`https://file:///`。

**Comment by leon-kfd** [comment]
网页无法访问到本地电脑的资源，JS `window.open`和`<a>`标签都不行，会报`Not allowed to load local resource`
![image](https://github.com/leon-kfd/Dashboard/assets/30256102/923dd1f8-4c72-435d-ba54-a1aa0ce65602)

**Comment by fxzxmicah** [comment]
和这没关系吧？比如我自己写了一个html的js小工具，想添加到书签，就不行。

**Comment by leon-kfd** [comment]
当前扩展没有申请任何权限。
你可以尝试用nignx/apache等软件挂载你的html到本地localhost服务，或者直接上vercel、githubPage等云服务平台

**Comment by fxzxmicah** [comment]
那可不可以用data协议？`data:text/html`这样？

**Comment by leon-kfd** [comment]
![image](https://github.com/leon-kfd/Dashboard/assets/30256102/727b05e4-adc5-47cf-b1cd-a24f4cec9f6e)
![image](https://github.com/leon-kfd/Dashboard/assets/30256102/78549e40-c1ed-4e64-b7a7-3bd16b9f8b07)
